name: dev_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.0
  - requests
  - uvicorn
  - gunicorn
  - git
  - pip
  - pip:
      - httpx
      - pytest
      - fastapi
      - fastapi[standard]
      - pre-commit
      - black
      - flake8
      - numpy==1.26.4
      - pandas==2.2.3
      - dvc==3.59.1
      - scikit-learn==1.6.1
