name: dev_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.0
  - requests
  - uvicorn
  - gunicorn
  - git
  - pip
  - pip:
      - fastapi[standard]
      - pre-commit
      - mlflow==2.20.0
      - numpy==1.26.4
      - pandas==2.2.3
      - fastapi==0.115.11
      - pytest==8.3.5
      - dvc==3.59.1
      - scikit-learn==1.6.1

