name: Pytest and flake8

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10","3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: changer directory
      run: cd starter    
    - name: Install dependencies from pyproject.toml and update pip
      run: |
        python -m pip install --upgrade pip
        pip install e . 
    - name: run pytest and flake8 from pre-commit 
      run: |
        pre-commint run --all-files
